# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TaulesTramitExpro
                                 A QGIS plugin
 Gestiona els taules de la tramitació de les expropiacions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-01
        copyright            : (C) 2024 by David Castellvell Buchaca
        email                : dcastellvell@gencat.cat
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TaulesTramitExpro class from file TaulesTramitExpro.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .taules_tramit import TaulesTramitExpro
    return TaulesTramitExpro(iface)
