# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TaulesTramitExproDialog
                                 A QGIS plugin
 Gestiona els taules de la tramitació de les expropiacions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-01
        git sha              : $Format:%H$
        copyright            : (C) 2024 by David Castellvell Buchaca
        email                : dcastellvell@gencat.cat
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtWidgets import QDialog, QCheckBox

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'taules_tramit_dialog_base.ui'))


class TaulesTramitExproDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(TaulesTramitExproDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        
        # Obtenir els checkbox del fitxer .ui
        self.checkBox_urg = self.findChild(QCheckBox, 'checkBox_urg')
        self.checkBox_ord = self.findChild(QCheckBox, 'checkBox_ord')

        # Verificar si els checkbox s'han trobat correctament
        if self.checkBox_urg is None:
            print("No s'ha trobat checkBox_urg")
        if self.checkBox_ord is None:
            print("No s'ha trobat checkBox_ord")

        # Connectar els senyals de toggled amb les funcions
        if self.checkBox_urg is not None:
            self.checkBox_urg.toggled.connect(self.on_checkBox_urg_toggled)
        if self.checkBox_ord is not None:
            self.checkBox_ord.toggled.connect(self.on_checkBox_ord_toggled)


        self.setupUi(self)
        
    def on_checkBox_urg_toggled(self, checked):
        if checked:
            self.checkBox_ord.setChecked(False)

    def on_checkBox_ord_toggled(self, checked):
        if checked:
            self.checkBox_urg.setChecked(False)
